<?php
function requestmodule_menu() {
    $items = array();

    $items['request_module/request_form'] = array(
        'title' => 'Request Form',
        'page callback' => 'say_request_form',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_request_form() {
 
$to = (isset($_POST) && $_POST['site_email'] !="") ? $_POST['site_email'] : "bhidev2015@gmail.com"; 



// subject
$subject = 'Materials Request from Galderma Website';

// message
$message = '
  <p>The following are the details of the request.</p>
  <table>
    <tr>
      <td>Material Name : '.$_POST['material_name'] .'</td>
    </tr>
   <tr>
      <td>Number Required : '.$_POST['number_required'] .'</td>
    </tr>
    <tr>
      <td>Delivery Address : '.$_POST['delivery_address'] .'</td>
    </tr>
    <tr>
      <td>Additional Information : '.$_POST['additional_information'] .'</td>
    </tr>
  </table>
';

// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

// Additional headers
$headers .= 'From:w-galderma@ls2.phases.dk' . "\r\n";

/*
$headers .= 'To: Mary <mary@example.com>, Kelly <kelly@example.com>' . "\r\n";
$headers .= 'From: Birthday Reminder <birthday@example.com>' . "\r\n";
$headers .= 'Cc: birthdayarchive@example.com' . "\r\n";
$headers .= 'Bcc: birthdaycheck@example.com' . "\r\n";
*/

// Mail it
if(@mail($to, $subject, $message, $headers)){
      echo "Request  has been successfully sent.";

}else{
      echo "Request  is not sent. Please try again later.";
} 
 exit;
 
}


/*
drupal_mail('my_form', 'some_mail_key', $valid_email, language_default(), $params, $from, TRUE);

function my_form() {
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#size' => '20',
    '#attributes' =>array('placeholder' => t('E-mail address'))
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Subscribe'),
  );
  return $form;
}



function my_form_validate($form, &$form_state) {
  $valid_email = $form_state['values']['email'];
  if (!valid_email_address($valid_email)) {
  form_set_error('email', 'Sorry. Your email address,' . $valid_email . ', is not valid. Please submit a valid E-mail address.');
  }
}

function my_form_mail($key, &$message, $params) {

  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8;',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
}


function my_form_submit($form, &$form_state) {
    $valid_email = $form_state['values']['email'];
    $from = 'noreply@example.com';
    $body[] = 'Email: '.$valid_email.'URL: '.request_uri();
    $to = 'example@example.com'; // Set this email address - emails will be sent to this email address! 
    $params = array(
    'body' => $body,
    'subject' => 'Website Information Request',
    );
 
    if (drupal_mail('my_form', 'some_mail_key', $to, language_default(), $params, $from, TRUE))
    {
        drupal_set_message('Thanks, we will be in contact with more information soon.');     
    } else {
        drupal_set_message('There was an error subscribing you. Please try again later');
    }
}
//return drupal_render(drupal_get_form('my_form')); 
*/